django-adminlte/core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView,LogoutView
from admin_adminlte import views

urlpatterns = [
    
    # 
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/register/', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('inventario/', include('inventario.urls', namespace='inventario')),
    path('personas/', include('personas.urls', namespace='personas')),
    path('licencias/', include('licencias.urls', namespace='licencias')),
    
    path('', include('home.urls')),
    path('', include('admin_adminlte.urls')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

django-adminlte/licencias/urls.py
from django.urls import path
from licencias.views import *

app_name = "licencias"
urlpatterns = [
    path("", LicenciasListView.as_view(), name="index"),
    path("eliminar/<int:pk>", LicenciassDeleteView.as_view(), name="eliminar"),
    path("crear", LicenciasCreateView.as_view(), name="crear"),
    path("editar/<int:pk>", LicenciasUpdateView.as_view(), name="editar"),
    
    path("asignar", AsignarLicenciasView.as_view(), name="asignar"),
]

django-adminlte/licencias/models.py
from datetime import date, timedelta

from django.contrib.auth import get_user
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from inventario.models import Software
from personas.models import Persona


class TipoLicencia(models.Model):
    tipo = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.tipo

class EstadoLic(models.Model):
    estado = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.estado

class Licencia(models.Model):
    nombre = models.CharField(max_length=100, verbose_name='Nombre de la licencia')
    numero_identificacion = models.CharField(max_length=100, verbose_name='Número de identificación',unique=True)
    software = models.ForeignKey(Software, on_delete=models.CASCADE, related_name="licencias")
    tipo_licencia = models.ForeignKey(TipoLicencia, on_delete=models.CASCADE, verbose_name='Tipo de licencia')
    fecha_activacion = models.DateField(auto_now_add=True, verbose_name='Fecha de activación')
    fecha_vencimiento = models.DateField(default=date.today() + timedelta(days=365), editable=False,verbose_name='Fecha de vencimiento')  
    observacion = models.TextField(verbose_name='Observación', null=True,blank=True)
    estado = models.ForeignKey(EstadoLic, on_delete=models.PROTECT, verbose_name='Estado de la licencia')
    asignada = models.BooleanField(default=False )
   
    def __str__(self):
        return f'{self.nombre} - {self.numero_identificacion} -software: {self.software.marca}  {self.software.version}'
    
    # def get_absolute_url(self):
    #     return reverse("licencias: index", kwargs={"id": self.id})
    
class LicenciaUsuario(models.Model):
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE,related_name='personas_asignadas')
    licencia = models.OneToOneField(Licencia, on_delete=models.CASCADE,  null=True, blank=True, related_name='licencia_asignada')
    fecha_asignada = models.DateField(verbose_name='Fecha de asignación')
    observacion = models.TextField(max_length=100, verbose_name='Observación',null=True, blank=True)
    fecha_registro = models.DateTimeField(auto_now=True, verbose_name='Fecha de registro')
    creado_por=models.ForeignKey(User, on_delete=models.CASCADE)
    
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['persona', 'licencia'], 
                name='LicenciaUnica'
            )
        ]
    
    def __str__(self):
        return f'{self.persona.nombre} {self.persona.apellido} '
    
    def clean(self):
        if not self.licencia:
            raise ValidationError('Debe seleccionar una licencia.')
        # Verificar si la persona ya tiene una licencia para el software específico
        if LicenciaUsuario.objects.filter(persona=self.persona, licencia__software=self.licencia.software).exists():
            raise ValidationError('Esta persona ya tiene una licencia para este software.')
    
@receiver(post_save, sender=LicenciaUsuario)
def update_licencia_asignada(sender, instance, **kwargs):
    licencia_usuario = instance
    licencia = licencia_usuario.licencia
    licencia.asignada = True
    licencia.save()

    

django-adminlte/licencias/forms.py
from django.forms import ModelForm
from .models import Licencia,LicenciaUsuario
from django.forms import ( DateInput, DateField, Textarea, Select)
class custom_form(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, DateField):
                field.widget = DateInput(
                    attrs={
                        "class": "datepicker",
                        "data-toggle": "datetimepicker",
                        "data-target": "#id_" + field_name,
                    }
                )
            if field_name == "observacion":
                field.widget.attrs["rows"] = 5
                
class Licenciaform(custom_form):
    class Meta:
        model = Licencia
        fields = ['nombre', 'numero_identificacion', 'tipo_licencia', 'observacion', 'estado']
        exclude = ["fecha_activacion","fecha_vencimiento","asignada"]
        
        widgets = {
            "software": Select(attrs={
                "class":"select2",
                }),
        }
   
        
class LicenciaUsuarioform(custom_form):
    class Meta:
        model = LicenciaUsuario
        exclude = ["fecha_registro","creado_por"]
        
        widgets = {
            "observacion": Textarea(attrs={"cols": 80, "rows": 5}),
            "persona": Select(attrs={"class":"select2", "style": "width: 100%"}),
            "licencia": Select(attrs={"class":"select2", "style": "width: 100%", "disabled": "true" }),
        
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #self.fields['licencia'].queryset = Licencia.objects.none()

django-adminlte/licencias/views.py
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import HttpResponseRedirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .forms import *
from .models import  Licencia,LicenciaUsuario
from personas.models import Persona
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q
class LicenciasListView(LoginRequiredMixin, ListView):
    model: Licencia
    queryset = Licencia.objects.all()
    template_name = "licencia/licencia_list.html"
    

class LicenciasCreateView(LoginRequiredMixin,SuccessMessageMixin, CreateView):
    model: Licencia
    form_class = Licenciaform
    template_name = "licencia/licencia_form.html"
    success_url = reverse_lazy("licencias:index")
    success_message = "  %(nombre)s ha sido creado con exito"
    
    def get_queryset(self):
        super().get_queryset()
        
        return 
    

class LicenciassDeleteView(LoginRequiredMixin,SuccessMessageMixin, DeleteView):
  model = Licencia
  template_name = "licencia/licencia_confirm_delete.html"
  success_url = reverse_lazy("licencias:index")
  success_message = "La persona ha sido eliminado exitosamente"
  
# keyword 'licencia' into field. Choices are: disponible, estado, estado_id, fecha_activacion, fecha_vencimiento, id, nombre, numero_identificacion, observacion, personasAsig, software, software_id, tipo_licencia, tipo_licencia_id, usuarios_asignados

  def post(self, request, *args, **kwargs):
        licencia = self.get_object() # 
        if Licencia.objects.filter(licencia=licencia).exists():
            # Si tiene personas asociadas, mostrar un mensaje de advertencia y cancelar la operación de eliminación
            messages.add_message(self.request, messages.WARNING, "La licencia tiene personas asociadas. No puede eliminarlo.")
            return HttpResponseRedirect(self.success_url)
        # Si no tiene facturas asociadas, eliminar el proveedor y redirigir a la lista de facturas
        return super().post(request, *args, **kwargs)
class LicenciasUpdateView(SuccessMessageMixin, UpdateView):
    model = Licencia
    form_class = Licenciaform
    template_name = "licencia/licencia_update_form.html"
    success_url = reverse_lazy("licencias:index")
    success_message = " Actualización realizada con exito de %(nombre)s "

    
class AsignarLicenciasView(LoginRequiredMixin,SuccessMessageMixin,CreateView):
    model = LicenciaUsuario
    form_class = LicenciaUsuarioform
    template_name = "licencia/licenciausuario_form.html"
    success_url = reverse_lazy("licencias:index")
    success_message = " Asignación de licencia a usuario ha sidorealizada con exito "
    
    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.creado_por = self.request.user
        return super().form_valid(form)
    
    def post(self, request, *args, **kwargs):
        # request.is_ajax() is deprecated since django 3.1
        is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
        if is_ajax:
            data = {}
            try:
                action = request.POST['action']
                persona_id = request.POST['id']
                if action == 'getLicenciasPersona':
                    data = []
                    for i in Licencia.objects.filter(asignada=False):
                            data.append({'id': i.pk, 'nombre': i.nombre})
                else:
                    data['error'] = 'Ha ocurrido un error'
            except Exception as e:
                data['error'] = str(e)
            return JsonResponse(data, safe=False)
        else:
            return super().post(request, *args, **kwargs)

django-adminlte/licencias/templates/licencia/licencia_confirm_delete.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %} Inventario {% endblock title %}
{% block extrastyle %}
{% endblock extrastyle %}
{% block bodyclass %}  {% endblock bodyclass %}
{% block content %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Personas</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Inicio</a></li>
            <li class="breadcrumb-item active">Personas</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container">
      <div class="container text-center">
      <div class="row justify-content-md-center">
        <!-- left column -->
        <div class="col-md-8">
          <!-- Horizontal Form -->
          <div class="card card-danger">
            <div class="card-header">
              <h3 class="card-title"><i class="fas fa-exclamation-triangle"></i>
              </h3>
            </div>
            <!-- /.card-header -->
            
            <!-- Default box -->
            <form method="post" class="card" enctype="multipart/form-data" >
                {% csrf_token %}
                <p class="mt-3">Está a punto de eliminar la persona <h3 class="fw-bolder accent-danger">{{object}}</h3>.</p><br>
                <p>Esta acción no se puede deshacer. ¿Está seguro de que desea continuar?</p>
                <div class="text-right">
                    <a href="{% url 'personas:index' %}" class="btn btn-outline-secondary shadow-2 mr-4">Cancelar</a>
                    <button type="submit" value="Delete" class="btn btn-danger shadow-2 mr-4">Eliminar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

django-adminlte/licencias/templates/licencia/licencia_form.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %} Crear Licencia. {% endblock title %}

{% block bodyclass %} hold-transition sidebar-mini {% endblock bodyclass %}
{% block extrastyle %}
<link rel="stylesheet" href="{% static 'plugins/select2/css/select2.css' %}">
{% endblock extrastyle %}
{% block content %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Ingresar nuevo Licencia</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              {% comment %} <li class="breadcrumb-item"><a href="{% url 'personas:index' %}">Home</a></li> {% endcomment %}
              <li class="breadcrumb-item active">IngresarLicencia</li>
              <li class="breadcrumb-item"><a href="{% url 'licencias:index' %}">Volver</a></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- Horizontal Form -->
            <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">Ingreso Licencias</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form class="form-horizontal" action="" method="post" >
                {% csrf_token %}
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-12">
                      <h2>Licencias</h2>
                      {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                      {% endfor %}

                      {% for field in form.visible_fields %}
                        <div class="form-group row">
                          <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label  }}</label>
                          <div class="col-sm-10">
                            {{ field|add_class:'form-control'  }}
                          </div>
                          {% for error in field.errors %}
                            <span class="help-block">{{ error }}</span>
                          {% endfor %}
                        </div>
                      {% endfor %}
                    </div>
                  </div>
                    
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-info">Aceptar</button>
                  <a href="{% url 'licencias:index' %}" class="btn btn-outline-secondary shadow-2 float-right mr-4">Cancelar</a>
                  
                </div>
                <!-- /.card-footer -->
              </form>
            </div>
            <!-- /.card -->
          </div>
          <!--/.col (left) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

  {% endblock content %}

  {% block extra_scripts %}
    <!-- Page specific script -->
    <script src="{% static 'plugins/select2/js/select2.js' %}"></script>
    <!-- Page specific script -->
    <script>
      $('.select2').select2({
        
      })
    </script>
  {% endblock extra_scripts %}

django-adminlte/licencias/templates/licencia/licencia_list.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %} Listado Licencias {% endblock title %}
{% block extrastyle %}
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
{% endblock extrastyle %}
{% block bodyclass %} hold-transition sidebar-mini {% endblock bodyclass %}
{% block content %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Licencias de CNX.</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'licencias:index' %}">Inicio</a></li>
              <li class="breadcrumb-item active">Licencia</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Listado de Licencias</h3>
                <div class="clearfix">
                  {% include 'includes/messages.html' %}
                 
                <span class= "float-right">
                <a  class="btn bg-primary btn-sm" title="add-licencia" href="{% url 'licencias:crear' %}">
                  <i class="fa fa-user-plus"></i>
                  Agregar
                </a>
                </span>
              </div>
            </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="licenciasTabla" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>Nombre</th>
                    <th>Número de identificación</th>
                    <th>Fecha de Activación</th>
                    <th>Fecha de Vencimiento</th>
                    <th>Software</th>
                    <th>Tipo</th>
                    <th>Estado</th>
                    <th>Asignada</th>
                    <th >Acción</th>
                  </tr>
                  </thead>
                  <tbody>
                    {% for licencia in object_list %}
                    <tr>
                      <td>{{ licencia.nombre}}</td>
                      <td>{{ licencia.numero_identificacion}}</td>
                      <td>{{ licencia.fecha_activacion|date:"SHORT_DATE_FORMAT"}}</td>
                      <td>{{ licencia.fecha_vencimiento|date:"SHORT_DATE_FORMAT"|default:"" }}</td>
                      <td>{{ licencia.software.marca}} {{ licencia.software.version}}</td>
                      <td>{{licencia.tipo_licencia.tipo }}</td>
                      <td>{{ licencia.estado.estado}}</td>
                      <td class="text-center">
                        {% if  licencia.asignada%}
                        <span style="color: green;">
                          <i class="fa fa-check-circle fa-2x " aria-hidden="true"></i>
                        </span>
                        {%else %}
                        <span style="color: red;">
                          <i class="fa fa-times-circle fa-2x " aria-hidden="true"></i>
                        </span>
                        {% endif %}

                      </td>
                      <td class="text-sm-right">
                        <a class="btn btn-info btn-sm" href="{% url 'licencias:editar' licencia.pk %}">
                            <i class="fas fa-pencil-alt">
                            </i>
                        </a>
                        <a class="btn btn-danger btn-sm" href="{% url 'licencias:eliminar' licencia.pk %}">
                            <i class="fas fa-trash"></i>
                        </a>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                  
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
{% endblock content %}
{% block extra_scripts %}
<!-- DataTables  & Plugins -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<!-- Page specific script -->
<script>
  $(function () {
    $("#licenciasTabla").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": [ "excel", "pdf", "print"]
    }).buttons().container().appendTo('#licenciasTabla_wrapper .col-md-6:eq(0)');
    
  });
</script>
{% endblock extra_scripts %}

django-adminlte/licencias/templates/licencia/licencia_update_form.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %} Actualizar Licencia {% endblock title %}

{% block extrastyle %}

<link rel="stylesheet" href="{% static 'plugins/select2/css/select2.css' %}">
{% endblock extrastyle %}
  
{% block bodyclass %} hold-transition sidebar-mini {% endblock bodyclass %}

{% block content %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Actualizar licencia</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Inicio</a></li>
              <li class="breadcrumb-item active">Actualizar licencia</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- Horizontal Form -->
            <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">Actualizar Licencia</h3>
              </div>
              <!-- /.card-header -->
              
              <!-- form start -->
              <form class="form-horizontal" action="" method="post" >
                {% csrf_token %}
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-12">
                      <h2>Licencia</h2>
                      {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                      {% endfor %}

                      {% for field in form.visible_fields %}
                        <div class="form-group row">
                          <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label  }}</label>
                          <div class="col-sm-10">
                            {{ field|add_class:'form-control'  }}
                          </div>
                          {% for error in field.errors %}
                            <span class="help-block">{{ error }}</span>
                          {% endfor %}
                        </div>
                      {% endfor %}
                    </div>
                </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-info">Actualizar</button>
                  <a href="{% url 'personas:index' %}" class="btn btn-outline-secondary shadow-2 float-right mr-4">Cancelar</a>
                </div>
                <!-- /.card-footer -->
              </form>
            </div>
            <!-- /.card -->
          </div>
          <!--/.col (left) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

  {% endblock content %}

  {% block extra_scripts %}
  <script src="{% static 'plugins/select2/js/select2.js' %}"></script>
    <!-- Page specific script -->
    <script>
      $('.select2').select2()
    </script>
  {% endblock extra_scripts %}

django-adminlte/licencias/templates/licencia/licenciausuario_form.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %} Asignar Licencias {% endblock title %}

{% block bodyclass %} hold-transition sidebar-mini {% endblock bodyclass %}
{% block extrastyle %}
<link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
{% endblock extrastyle %}
{% block content %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Asignar Licencia a persona</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              {% comment %} <li class="breadcrumb-item"><a href="{% url 'personas:index' %}">Home</a></li> {% endcomment %}
              <li class="breadcrumb-item active">Asignar Licencia</li>
              <li class="breadcrumb-item"><a href="{% url 'licencias:index' %}">Vover</a></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- Horizontal Form -->
            <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">Asignar licencias</h3>
                <div class="clearfix">
                  {% include 'includes/messages.html' %}
                </div>

              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form class="form-horizontal" method="post" >
                {% csrf_token %}
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-12">
                      <h2>Asignar Licencias</h2>
                      {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                      {% endfor %}

                      {% for field in form.visible_fields %}
                        <div class="form-group row">
                          <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label  }}</label>
                          <div class="col-sm-10">
                            {{ field|add_class:'form-control'  }}
                          </div>
                          {% for error in field.errors %}
                            <span class="help-block">{{ error }}</span>
                          {% endfor %}
                        </div>
                      {% endfor %}
                    </div>
                  </div>
                    
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-info">Aceptar</button>
                  <a href="{% url 'licencias:index' %}" class="btn btn-outline-secondary shadow-2 float-right mr-4">Cancelar</a>
                  
                </div>
                <!-- /.card-footer -->
              </form>
            </div>
            <!-- /.card -->
          </div>
          <!--/.col (left) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

  {% endblock content %}

  {% block extra_scripts %}
  <script src="{% static 'plugins/select2/js/select2.full.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'plugins/select2/js/i18n/es.js' %}">
  <script src="{% static 'plugins/moment/moment-with-locales.min.js' %}"></script>
  <script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
  <script>
    $(function () {

    $('.select2').select2({
      language: "es",
      width: 'resolve',
    });
    var select_licencia = $('select[name="licencia"]');
    $("select[name='persona']").on("change", function() {
      var id= $(this).val();
      var options = '<option value = "">-----------</option>'
      if ( id == '') {
        select_persona.html(option);
        return false;
      }
      $.ajax({
        url: window.location.patname,
        type: 'POST',
        data: {
          'id': id,
          'action': 'getLicenciasPersona'
          },
          datatype: 'json',
        }).done(function (data) {
          if (!data.hasOwnProperty('error')) {
            if (data.length > 0){
              $.each(data, function (key, value) {
                options+='<option value="'+value.id+'">'+value.nombre+'</option>';
            });
            select_licencia.prop("disabled", false);
            } else{
              alert('No se encontraron licencias para esta persona o  no disponibles');
            };
            return false;
          }
          message_error(data.error);
        }).fail(function (jqXHR, textStatus, errorThrown) {
          alert(textStatus + ': ' + errorThrown);
        }).always(function (data) {
        select_licencia.html(options);
        });

    });
    
      $('.datepicker').datetimepicker({
        format: 'DD/MM/YYYY'
      }); 
  });
    </script>
  {% endblock extra_scripts %}