django-adminlte/core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView,LogoutView
from admin_adminlte import views

urlpatterns = [
    
    # 
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/register/', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('inventario/', include('inventario.urls', namespace='inventario')),
    path('personas/', include('personas.urls', namespace='personas')),
    path('licencias/', include('licencias.urls', namespace='licencias')),
    
    path('', include('home.urls')),
    path('', include('admin_adminlte.urls')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

django-adminlte/inventario/urls.py
from django.urls import path
from inventario.views import *

app_name = 'inventario'
urlpatterns = [
    path("", InventarioListViews.as_view(), name="index"),
    path("crear", InventarioCreateView.as_view(), name="crear"),
    path("editar/<int:pk>", InventarioUpdateView.as_view(), name="editar"),
    path("eliminar/<int:pk>", InventarioDeleteView.as_view(), name="eliminar"), 
    #path("detalle/<int:id>", InventarioDetailView.as_view(), name="detalle"),

    ## Dispositivos
    path("dispositivo/", DispositivoListViews.as_view(), name="index_disp"),
    path("dispositivocards/", DispositivoCardsListViews.as_view(), name="index_disp_cards"),
    path("dispositivo/crear", DispositivoCreateView.as_view(), name="crear_disp"),
    path("dispositivo/editar/<int:pk>", DispositivoUpdateView.as_view(), name="editar_disp"),
    path("dispositivo/eliminar/<int:pk>", DispositivoDeleteView.as_view(), name="eliminar_disp"),
    path("dispositivo/<int:pk>/", DispositivoDetailView.as_view(), name="detalle_disp"),
    
    ## Software
    path("software/", SoftwareListViews.as_view(), name="index_soft"),
    path("software/crear", SoftwareCreateView.as_view(), name="crear_soft"),
    path("software/editar/<int:pk>", SoftwareUpdateView.as_view(), name="editar_soft"),
    path("software/eliminar/<int:pk>", SoftwareDeleteView.as_view(), name="eliminar_soft"),
    #path("software/detalle/<int:id>", SoftwareDetailView.as_view(), name="detalle_soft"),
    
    ##Proveedor
    path("proveedor/", ProveedorListViews.as_view(), name="index_prove"),
    path("proveedor/crear", ProveedorCreateView.as_view(), name="crear_prove"),
    path("proveedor/editar/<int:pk>", ProveedorUpdateView.as_view(), name="editar_prove"),
    path("proveedor/eliminar/<int:pk>", ProveedorDeleteView.as_view(), name="eliminar_prove"),
    #path("proveedor/detalle/<int:id>", ProveedorDetailView.as_view(), name="detalle_prove"),
    
    ##Factura
    path("factura/", FacturaListViews.as_view(), name="index_factu"),
    path("factura/crear", FacturaCreateView.as_view(), name="crear_factu"),
    path("factura/editar/<int:pk>", FacturaUpdateView.as_view(), name="editar_factu"),
    path("factura/eliminar/<int:pk>", FacturaDeleteView.as_view(), name="eliminar_factu"),
    #path("factura/detalle/<int:id>", FacturaDetailView.as_view(), name="detalle_factu"),
    
    
    path('avisos/', AvisosVencimientoView.as_view(), name='avisos_vencimiento'),
]

django-adminlte/inventario/forms.py
from cProfile import label
from django.forms import ModelForm
from django.forms import (
    DateInput,
    DateField,
    Textarea,
    Select, BooleanField, CheckboxInput

)
from django.urls import reverse_lazy


from .models import Factura, Inventario, Dispositivo, Proveedor, Software
from licencias.models import Licencia
from django.contrib.contenttypes.forms import generic_inlineformset_factory
from django.forms import inlineformset_factory

class custom_form(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"
        for field_name, field in self.fields.items():
            if isinstance(field, DateField):
                field.widget = DateInput(
                    attrs={
                        "class": "form-control datepicker",
                        "data-toggle": "datetimepicker",
                        "data-target": "#id_" + field_name,
                    }
                )
            if isinstance(field, BooleanField):
                field.widget = CheckboxInput(
                    attrs={
                        "class": "form-check-input",
                    }
                )
            if field_name == "observacion":
                field.widget.attrs["rows"] = 3

class Inventario_form(custom_form):
    class Meta:
        model = Inventario
        fields = "__all__"
        exclude = ("id",)
        widgets = {
            "observacion": Textarea(attrs={"cols": 80, "rows": 3}),
        }
# ---- Formulario de Dispositivo ---
class Dispositivo_form(custom_form):

    class Meta:
        model = Dispositivo
        fields = "__all__"
        widgets = {
            "observacion": Textarea(attrs={"cols": 80, "rows":3}),
        }
        
DispositivoInlineFormSet = generic_inlineformset_factory(
    Inventario,
    form=Dispositivo_form,
    fields="__all__",
    exclude = ("id", "fecha_caducidad"),
    can_delete=False,
    extra=1,
    
)

DispositivoInlineFormSetUpdate = generic_inlineformset_factory(
    Inventario,
    form=Dispositivo_form,
    fields="__all__",
    exclude =("id","fecha_caducidad"),
    can_delete=False,
    extra=0,
)

# ---- Formulario de Software ---
from licencias.forms import Licenciaform
class Software_form(custom_form):
    class Meta:
        model = Software
        fields = ['marca', 'version', 'fecha_instalacion', 'cuenta_asociada', 'cantidad_licencias']
        
      

class Proveedor_form(custom_form):
    class Meta:
        model = Proveedor
        fields = "__all__"
        
        
from django_addanother.widgets import AddAnotherWidgetWrapper     

class Factura_form(custom_form):
    class Meta:
        model = Factura
        fields = "__all__"
        widgets = {
                'proveedor': AddAnotherWidgetWrapper(
                    Select(attrs={'class': 'form-control select2'}, ),
                    reverse_lazy('inventario:crear_prove'),
                ),
            }
        
SoftwareInlineFormSet = generic_inlineformset_factory(
    Inventario,
    form = Software_form,
    fields = "__all__",
    exclude = ("id","fecha_caducidad",),
    can_delete=False,
    extra=0,
)

SoftwareInlineFormSetUpdate = generic_inlineformset_factory(
    Inventario,
    form = Software_form,
    fields = ("__all__"),
    exclude = ("id", "fecha_caducidad",),
    can_delete=False,
    extra=1,
)
        
# LicenciaFormSet = inlineformset_factory(
#     Software,  # Modelo padre
#     Licencia,  # Modelo hijo
#     fields=('nombre', 'numero_identificacion', 'tipo_licencia', 'observacion', 'estado'),  # Campos a mostrar en el formulario
#     extra=1, # Número inicial de formularios en línea
#     exclude = ["id"]
# )

# class SoftwarelicenciaForm(custom_form):
#     class Meta:
#         model = Software
#         fields = ['marca', 'version', 'fecha_instalacion', 'cuenta_asociada', ]

django-adminlte/inventario/views.py
from datetime import date, timedelta
from django.db import transaction
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import ExpressionWrapper, F, fields
from django.shortcuts import HttpResponseRedirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django_addanother.views import UpdatePopupMixin

from .forms import *
from .models import Dispositivo, Factura, Inventario, Proveedor, Software


def annotate_inventory_fields(queryset):
    queryset = queryset.annotate(
            nombre_inventario=F('inventario__nombre'),
            valor_inventario=F('inventario__valor'),
            disponible_inventario =F('inventario__disponible'),
            duracion_inventario =F('inventario__duracion'),
            estado_inventario =F('inventario__estado__estado'),
            fecha_registro_inventario =F('inventario__fecha_registro'),
            fecha_entrega_inventario =F('inventario__fecha_entrega'),
            fecha_caducidad_inventario=F('inventario__fecha_caducidad'),
            observacion_inventario =F('inventario__observacion'),
            #factura
            factura_inventario = F('inventario__factura__factura'),
            fecha_registro_factura_inventario = F('inventario__factura__fecha_factura'),
            fecha_factura_inventario = F('inventario__factura__fecha_registro'),
            proveedor_factura_inventario = F('inventario__factura__proveedor__nombre'),
            orden_de_compra_inventario = F('inventario__factura__orden_de_compra'),
            #otras
            tiempo_de_vida_inventario=ExpressionWrapper( date.today() -
                F('inventario__factura__fecha_factura'),
                output_field=fields.DurationField()
            ),        
    )
    return queryset

class InventarioListViews(SuccessMessageMixin,ListView):
    models: Inventario
    queryset = Inventario.objects.all()
    template_name = 'inventario/inventario_list.html'
class InventarioCreateView(SuccessMessageMixin,CreateView):
    model= Inventario
    template_name = "inventario/inventario_form.html"
    success_url = reverse_lazy("inventario:index")
    success_message = "%(nombre)s ha sido creado con exito."
    
class InventarioUpdateView(SuccessMessageMixin,UpdateView):
    model = Inventario
    form_class = Inventario_form
    success_url = reverse_lazy("inventario:index")
    template_name = "inventario/inventario_update_form.html"
    success_message = " ha sido actualizado con exito."

class InventarioDeleteView(SuccessMessageMixin,DeleteView):
    model= Inventario
    success_url = reverse_lazy("inventario:index")
    template_name = "inventario/inventario_delete.html"
    success_message = "%(nombre) ha sido eliminado exitosamente."
    
########################### ---- Vistas para Dispositivos -----    
class DispositivoListViews(LoginRequiredMixin,ListView):
    models: Dispositivo
    queryset = Dispositivo.objects.all()
    template_name = 'dispositivo/dispositivo_list.html'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = annotate_inventory_fields(queryset)
        return queryset

class DispositivoCardsListViews(LoginRequiredMixin,ListView):
    models: Dispositivo
    queryset = Dispositivo.objects.all()
    template_name = 'dispositivo/dispositivo_list_cards.html'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = annotate_inventory_fields(queryset)
        return queryset
 

class DispositivoCreateView(LoginRequiredMixin,SuccessMessageMixin,CreateView):
    model= Dispositivo
    template_name = "dispositivo/dispositivo_form.html"
    form_class = Dispositivo_form
    formset = DispositivoInlineFormSet
    success_url = reverse_lazy("inventario:index_disp")
    success_message = "%(modelo)s ha sido creado con exito."
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            formset = DispositivoInlineFormSet(self.request.POST)
        else:
            formset = DispositivoInlineFormSet()
        context['formset'] = formset
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            self.object.tipo='H'
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form))
    
    
class DispositivoUpdateView(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
    model = Dispositivo
    form_class = Dispositivo_form
    success_url = reverse_lazy("inventario:index_disp")
    template_name = "dispositivo/dispositivo_update_form.html"
    success_message = "Ha sido actualizado con exito."
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset = DispositivoInlineFormSetUpdate(instance = self.object)
        return self.render_to_response(self.get_context_data(form = form, formset = formset))

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset = DispositivoInlineFormSet(self.request.POST, instance=self.object)
        if (form.is_valid() and formset.is_valid()):
            return self.form_valid(form, formset)
        return self.form_invalid(form, formset)

    def form_valid(self, form, formset):
        self.object = form.save()
        formset.instance = self.object
        formset.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, formset):
        return self.render_to_response(self.get_context_data(form=form, formset_disp=formset))
    
class DispositivoDeleteView(LoginRequiredMixin,SuccessMessageMixin,DeleteView):
    model= Dispositivo
    success_url = reverse_lazy("inventario:index_disp")
    template_name = "dispositivo/dispositivo_confirm_delete.html"
    success_message = " Ha sido eliminado exitosamente."
    
    
class DispositivoDetailView(LoginRequiredMixin,DetailView):
    model = Dispositivo
    template_name = "dispositivo/dispositivo_detail.html"
    
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = annotate_inventory_fields(queryset)
        return queryset

########################### ---- Vistas para Software -----    
class SoftwareListViews(LoginRequiredMixin,SuccessMessageMixin,ListView):
    models: Software
    queryset = Software.objects.all()
    template_name = 'software/software_list.html'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = annotate_inventory_fields(queryset)
        return queryset
    
class SoftwareCreateView(LoginRequiredMixin,SuccessMessageMixin,CreateView):
    model= Software
    template_name = "software/software_form.html"
    form_class = Software_form
    formset = SoftwareInlineFormSet
    success_url = reverse_lazy("inventario:index_soft")
    success_message = "Ha sido creado con exito."
    
    def get_context_data(self, **kwargs):
        context = super(SoftwareCreateView, self).get_context_data(**kwargs)
        if self.request.POST:
            context['inventario_formset']= SoftwareInlineFormSet(self.request.POST)
        else:
            context['inventario_formset'] = SoftwareInlineFormSetUpdate()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        inventario_formset = context['inventario_formset']
        if inventario_formset.is_valid():
            self.object = form.save()
            inventario_formset.instance = self.object
            inventario_formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form))
    
class SoftwareUpdateView(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
    model = Software
    form_class = Software_form
    success_url = reverse_lazy("inventario:index_soft")
    template_name = "software/software_update_form.html"
    success_message = "Ha sido actualizado con exito."
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset = SoftwareInlineFormSet(instance = self.object)
        return self.render_to_response(self.get_context_data(form = form, formset = formset))

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset = SoftwareInlineFormSet(self.request.POST, instance=self.object)

        if (form.is_valid() and formset.is_valid()):
            return self.form_valid(form, formset)
        return self.form_invalid(form, formset)

    def form_valid(self, form, formset):
        self.object = form.save()
        formset.instance = self.object
        formset.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, formset):
        return self.render_to_response(self.get_context_data(form=form, formset_disp=formset))

class SoftwareDeleteView(LoginRequiredMixin,SuccessMessageMixin,DeleteView):
    model= Software
    success_url = reverse_lazy("inventario:index_soft")
    template_name = "software/software_confirm_delete.html"
    success_message = "Ha sido eliminado exitosamente."
    

django-adminlte/inventario/templates/inventario/inventario_list.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %} Inventario {% endblock title %}
{% block extrastyle %}
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
{% endblock extrastyle %}
{% block bodyclass %} hold-transition sidebar-mini {% endblock bodyclass %}
{% block content %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Inventario</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Inicio</a></li>
              <li class="breadcrumb-item active">Inventario</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Listado de Inventario</h3>
                <span class= "float-right">
                <a  class="btn bg-primary btn-sm" title="add-inven" href="{% url 'inventario:crear' %}">
                  <i class="fa fa-user-plus"></i>
                  Agregar
                </a>
                </span>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="inventarioTabla" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>Nombre</th>
                    <th>Valor</th>
                    <th>Número_orden</th>
                    <th>Disponible</th>
                    <th >Estado</th>
                    <th >Proveedor</th>
                    <th >Factura</th>
                    <th >Persona Asignada</th>
                    <th >Gerencia</th>
                    <th >Acción</th>


                  </tr>
                  </thead>
                  
                  <tbody>
                    {% for inventario in object_list %}
                    <tr>
                      
                      <td>{{ inventario.nombre}}</td>
                      <td>{{ inventario.valor}}</td>
                      <td>{{ inventario.numero_orden}}</td>
                      <td>{{ inventario.disponible}}</td>
                      <td>{{ inventario.estado}}</td>
                      <td>{{ inventario.proveedor}}</td>
                      <td>{{ inventario.factura}}</td>
                      <td>{{ inventario.persona_asignada}}</td>

                      <td>{{ inventario.persona_asignada.gerencia}}</td>
                      <td class="text-sm-right">
                        <a class="btn btn-info btn-sm" href="{% url 'inventario:editar' inventario.pk %}">
                            <i class="fas fa-pencil-alt">
                            </i>
                        </a>
                        <a class="btn btn-danger btn-sm" href="{% url 'inventario:eliminar' inventario.pk %}">
                            <i class="fas fa-trash">
                            </i>
                            </a>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                  
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
{% endblock content %}
{% block extra_scripts %}
<!-- DataTables  & Plugins -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<!-- Page specific script -->
<script>
  $(function () {
    $("#personaTabla").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#personaTabla_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
{% endblock extra_scripts %}

django-adminlte/inventario/templates/inventario/inventario_update_form.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %} General Form Elements {% endblock title %}

{% block extrastyle %}

<link rel="stylesheet" href="{% static 'plugins/select2/css/select2.css' %}">
{% endblock extrastyle %}
  
{% block bodyclass %} hold-transition sidebar-mini {% endblock bodyclass %}

{% block content %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Actualizar Inventario</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Inicio</a></li>
              <li class="breadcrumb-item active">Actualizar Inventario</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- Horizontal Form -->
            <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">Actualizar Inventarios</h3>
              </div>
              <!-- /.card-header -->
              
              <!-- form start -->
              <form class="form-horizontal" action="" method="post" >
                {% csrf_token %}
                <div class="card-body">
                  {{ form.as_div }}
                 
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-info">Actualizar</button>
                  <button type="submit" class="btn btn-default float-right">Cancelar</button>
                </div>
                <!-- /.card-footer -->
              </form>
            </div>
            <!-- /.card -->
          </div>
          <!--/.col (left) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

  {% endblock content %}

  {% block extra_scripts %}
  <script src="{% static 'plugins/select2/js/select2.js' %}"></script>
    <!-- Page specific script -->
    <script>
      $('.select2').select2()
    </script>
  {% endblock extra_scripts %}