django-adminlte/core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView,LogoutView
from admin_adminlte import views

urlpatterns = [
    
    # 
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/register/', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('inventario/', include('inventario.urls', namespace='inventario')),
    path('personas/', include('personas.urls', namespace='personas')),
    path('licencias/', include('licencias.urls', namespace='licencias')),
    
    path('', include('home.urls')),
    path('', include('admin_adminlte.urls')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

django-adminlte/personas/urls.py
from django.urls import path
from personas.views import *

app_name = "personas"
urlpatterns = [
    path("", PersonasListView.as_view(), name="index"),
    path("eliminar/<int:pk>", PersonasDeleteView.as_view(), name="eliminar"),
    path("crear", PersonasCreateView.as_view(), name="crear"),
    path("editar/<int:pk>", PersonasUpdateView.as_view(), name="editar"),
    
    ## Departamentos
    path("dpto/", DepartamentoListView.as_view(), name="dpto"),
    path(
        "dpto/eliminar/<int:pk>",
        DepartamentoDeleteView.as_view(),
        name="eliminar_dpto",
    ),
    path("dpto/crear", DepartamentoCreateView.as_view(), name="crear_dpto"),
    path(
        "dpto/editar/<int:pk>",
        DepartamentoUpdateView.as_view(),
        name="editar_dpto",
    ),
]

django-adminlte/personas/models.py
from django.db import models
from django.urls import reverse
from django.forms import model_to_dict
class Departamento(models.Model): # nombre de  la genencia.
    gerencia = models.CharField(max_length=100)

    def __str__(self):
        return self.gerencia    

class Persona(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    email = models.EmailField()
    usuario = models.CharField(max_length=100, null=True,blank=True)
    gerencia = models.ForeignKey(Departamento, on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.nombre} {self.apellido}"
    
    def toJSON(self):
        item = model_to_dict(self)
        return item

    @property
    def nombre_completo(self):
        nombre_completo = "%s %s" % (self.nombre, self.apellido)
        return nombre_completo.strip()

    def get_absolute_url(self):
        return reverse("personas:editar", kwargs={"id": self.id})
    
    

django-adminlte/personas/forms.py
from mimetypes import init
from turtle import textinput
from django import forms
from django.forms import ModelForm
from .models import Persona, Departamento
from django import forms

class Personas_form(ModelForm):
    class Meta:
        model = Persona
        fields = "__all__"
        
class Departamento_form(ModelForm):
    class Meta:
        model = Departamento
        fields = ["gerencia"]
        labels = {
            "gerencia":"Gerencia",
        }
    Widget = {
        "gerencia": forms.TimeInput(
            attrs={
                "class":"form-control",
                "placeholder": "gerencia",
                "required":"true"
            }
        )
    }
    
    
    
    
    
    
    
    

django-adminlte/personas/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import HttpResponseRedirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .forms import *
from .models import  Departamento, Persona


class PersonasListView(LoginRequiredMixin, ListView):
    model: Persona
    queryset = Persona.objects.all()
    template_name = "personas/personas_list.html"

class PersonasCreateView(SuccessMessageMixin, CreateView):
    model: Persona
    form_class = Personas_form
    template_name = "personas/personas_form.html"
    success_url = reverse_lazy("personas:index")
    success_message = "  %(nombre)s ha sido creado con exito"


class PersonasDeleteView(SuccessMessageMixin, DeleteView):
    model = Persona
    template_name = "personas/personas_confirm_delete.html"
    success_url = reverse_lazy("personas:index")
    success_message = "La persona ha sido eliminado exitosamente"


class PersonasUpdateView(SuccessMessageMixin, UpdateView):
    model = Persona
    form_class = Personas_form
    template_name = "personas/personas_update_form.html"
    success_url = reverse_lazy("personas:index")
    success_message = " Actualización realizada con exito de %(nombre)s "

    # Departamento
class DepartamentoListView(LoginRequiredMixin, ListView):
    model: Departamento
    queryset = Departamento.objects.all()
    template_name = "personas/dpto/departamento_list.html"
    

class DepartamentoCreateView(SuccessMessageMixin,CreateView):
    model: Departamento
    form_class = Departamento_form
    template_name = "personas/dpto/departamento_form.html"
    success_message = " La gerencia ha sido creada con exito"
    success_url = reverse_lazy("personas:dpto")


class DepartamentoDeleteView(SuccessMessageMixin,DeleteView):
    model = Departamento
    template_name = "personas/dpto/departamento_confirm_delete.html"
    success_url = reverse_lazy("personas:dpto")
    success_message = "La gerencia ha sido eliminado exitosamente"
    
    def post(self, request, *args, **kwargs):
        gerencia = self.get_object() # Verificar si el departamento tiene personas asociadas
        if Departamento.objects.filter(gerencia=gerencia).exists():
            # Si tiene personas asociadas, mostrar un mensaje de advertencia y cancelar la operación de eliminación
            messages.add_message(self.request, messages.WARNING, "El departamento tiene personas asociadas. No puede eliminarlo.")
            return HttpResponseRedirect(self.success_url)
        # Si no tiene facturas asociadas, eliminar el proveedor y redirigir a la lista de facturas
        return super().post(request, *args, **kwargs)


class DepartamentoUpdateView(SuccessMessageMixin,UpdateView):
    model = Departamento
    form_class = Departamento_form
    template_name = "personas/dpto/departamento_update_form.html"
    success_url = reverse_lazy("personas:dpto")
    success_message = "La gerencia ha sido actualizada exitosamente"

django-adminlte/personas/templates/personas/dpto/departamento_confirm_delete.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %} Inventario {% endblock title %}
{% block extrastyle %}
{% endblock extrastyle %}
{% block bodyclass %}  {% endblock bodyclass %}
{% block content %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Departamento</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Inicio</a></li>
            <li class="breadcrumb-item active">Departamento</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container">
      <div class="container text-center">
      <div class="row justify-content-md-center">
        <!-- left column -->
        <div class="col-md-8">
          <!-- Horizontal Form -->
          <div class="card card-danger">
            <div class="card-header">
              <h3 class="card-title"><i class="fas fa-exclamation-triangle"></i>
              </h3>
            </div>
            <!-- /.card-header -->
            
            <!-- Default box -->
            <form method="post" class="card" enctype="multipart/form-data" >
                {% csrf_token %}
                <p class="mt-3">Está a punto de eliminar el departamento <h3 class="fw-bolder accent-danger">{{object}}</h3>.</p><br>
                <p>Esta acción no se puede deshacer. ¿Está seguro de que desea continuar?</p>
                <div class="text-right">
                    <a href="{% url 'personas:dpto' %}" class="btn btn-outline-secondary shadow-2 mb-r">Cancelar</a>
                    <button type="submit" value="Delete" class="btn btn-danger shadow-2 mr-4">Eliminar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

django-adminlte/personas/templates/personas/dpto/departamento_form.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %} Crear Elemento. {% endblock title %}

{% block bodyclass %} hold-transition sidebar-mini {% endblock bodyclass %}
{% block extrastyle %}
<link rel="stylesheet" href="{% static 'plugins/select2/css/select2.css' %}">
{% endblock extrastyle %}
{% block content %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Ingresar Departamento</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              {% comment %} <li class="breadcrumb-item"><a href="{% url 'personas:index' %}">Home</a></li> {% endcomment %}
              <li class="breadcrumb-item active">Ingresar Departamento</li>
              <li class="breadcrumb-item"><a href="{% url 'personas:dpto' %}">Vover</a></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- Horizontal Form -->
            <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">Ingreso Personas</h3>
              </div>
              <!-- /.card-header -->
             
              <!-- form start -->
              <form class="form-horizontal" action="" method="post" >
                {% csrf_token %}
                <div class="card-body">
                  <div class="form-group row">
                    <label for="inputEmail3" class="col-sm-2 col-form-label">{{form.nombre.label_tag }}</label>
                    <div class="col-sm-10">
                      {{ form.nombre }}
                    </div>
                    {{ form.nombre.errors}}
                  </div>
                  <div class="form-group row">
                    <label  class="col-sm-2 col-form-label">{{form.apellido.label_tag }}</label>
                    <div class="col-sm-10">
                     {{ form.apellido }}
                    </div>
                    {{ form.apellido.errors}}
                  </div>
                  <div class="form-group row">
                    <label  class="col-sm-2 col-form-label">{{form.email.label_tag }}</label>
                    <div class="col-sm-10">
                     {{ form.email }}
                    </div>
                    {{ form.email.errors}}
                  </div>
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">{{form.gerencia.label_tag }}</label>
                    <div class="col-sm-10">
                     {{ form.gerencia }}
                    </div>
                    {{ form.gerencia.errors}}
                  </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-info">Aceptar</button>
                  <a href="{% url 'personas:dpto' %}" class="btn btn-outline-secondary shadow-2 mr-4">Cancelar</a>
                </div>
                <!-- /.card-footer -->
              </form>
            </div>
            <!-- /.card -->
          </div>
          <!--/.col (left) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

  {% endblock content %}

  {% block extra_scripts %}
    <!-- Page specific script -->
    <script src="{% static 'plugins/select2/js/select2.js' %}"></script>
    <!-- Page specific script -->
    <script>
      $('.select2').select2({
        
      })
    </script>
  {% endblock extra_scripts %}

django-adminlte/personas/templates/personas/dpto/departamento_list.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %} Listado Personas {% endblock title %}
{% block extrastyle %}
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
{% endblock extrastyle %}
{% block bodyclass %} hold-transition sidebar-mini {% endblock bodyclass %}
{% block content %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Personas</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Inicio</a></li>
              <li class="breadcrumb-item active">Áreas</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Listado de Departamentos</h3>
                <div class="clearfix">
                  {% include 'includes/messages.html' %}
                  <span class= "float-right">
               
                <a  class="btn bg-primary btn-sm" title="add-person" href="{% url 'personas:crear_dpto' %}">
                  <i class="fa fa-user-plus"></i>
                  Agregar
                </a>
                </span>
              </div>
            </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="dptoTabla" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>Nombre</th>
                    
                    <th >Acción</th>
                  </tr>
                  </thead>
                  <tbody>
                    {% for dpto in object_list %}
                    <tr>
                      <td>{{ dpto.gerencia}}</td>
                      
                      <td class="text-sm-right">
                        <a class="btn btn-info btn-sm" href="{% url 'personas:editar_dpto' dpto.pk %}">
                            <i class="fas fa-pencil-alt">
                            </i>
                        </a>
                        <a class="btn btn-danger btn-sm" href="{% url 'personas:eliminar_dpto' dpto.pk %}">
                            <i class="fas fa-trash">
                            </i>
                            </a>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                  
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
{% endblock content %}
{% block extra_scripts %}
<!-- DataTables  & Plugins -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<!-- Page specific script -->
<script>
  $(function () {
    $("#dptoTabla").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": True,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#dptoTabla_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
{% endblock extra_scripts %}

django-adminlte/personas/templates/personas/dpto/departamento_update_form.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %} General Form Elements {% endblock title %}

{% block extrastyle %}

<link rel="stylesheet" href="{% static 'plugins/select2/css/select2.css' %}">
{% endblock extrastyle %}
  
{% block bodyclass %} hold-transition sidebar-mini {% endblock bodyclass %}

{% block content %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Actualizar Departamento</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Inicio</a></li>
              <li class="breadcrumb-item active">Actualizar Departamento</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- Horizontal Form -->
            <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">Actualizar Departamento</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              
              <form class="form-horizontal" action="" method="post" >
                {% csrf_token %}
                <div class="card-body">
                  <div class="form-group row">
                    <label for="inputEmail3" class="col-sm-2 col-form-label">{{form.gerencia.label_tag }}</label>
                    <div class="col-sm-10">
                      {{ form.gerencia }}
                    </div>
                    {{ form.gerencia.errors}}
                  </div>
                  
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-info">Actualizar</button>
                  <a href="{% url 'personas:dpto' %}" class="btn btn-outline-secondary shadow-2 float-right mb-r">Cancelar</a>
                </div>
                <!-- /.card-footer -->
              </form>
            </div>
            <!-- /.card -->
          </div>
          <!--/.col (left) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

  {% endblock content %}

  {% block extra_scripts %}
  <script src="{% static 'plugins/select2/js/select2.js' %}"></script>
    <!-- Page specific script -->
    <script>
      $('.select2').select2()
    </script>
  {% endblock extra_scripts %}